### PR TITLE
Hybridpath guidance fix

### PR DESCRIPTION
**Pull request by Andeshog**
Changed u_desired to be a variable that is chosen by mission_planner. Right now it is defaulted at 0.25 m/s, but I will make an issue to link it to mission_planner. Everything works as intended now.

### CODE REVIEW

**Comment by alekskl01** [comment]
It does not seem to be able to update u_desired anywhere

**Review by alekskl01 — CHANGES_REQUESTED** [review]
It does not appear that u_desired can be updated.

**Comment by Andeshog** [comment]
> It does not appear that u_desired can be updated at all.

Are you refering to task #186 ?

**Comment by alekskl01** [comment]
> > It does not appear that u_desired can be updated at all.
> 
> Are you refering to task #186 ?

Yes, if this is simply a needed bugfix then i can merge.

**Review by alekskl01 — APPROVED** [review]

**Pull request merged**
